version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.2.0
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - USE_SINGLE_REGION=1
      - DEFAULT_REGION=us-east-1
      - DYNAMODB_SHARE_DB=${DYNAMODB_SHARE_DB-1}
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-1}
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - START_WEB=0
    volumes:
      - "./.data/localstack_main:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
# version: "3"

# services:
#   news:
#     build: .
#     image: tech_news_image
#     volumes:
#       - ./:/app
#     container_name: tech_news
#     tty: true # docker run -t
#     stdin_open: true # docker run -i
#     command: bash
#     restart: unless-stopped
#     depends_on:
#       - mongodb
#     environment:
#       - DB_HOST=mongodb
#     networks:
#       - tech_news_net

#   mongodb:
#     image: mongo:4.4.14
#     container_name: tech_news_db
#     volumes:
#       - ./:/app
#     restart: unless-stopped
#     ports:
#       - 27017:27017
#     networks:
#       - tech_news_net

# networks:
#   tech_news_net:
#     driver: bridge
