AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 3072
    Runtime: python3.9
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Sub ${AWS::StackName}

Resources:
  RealmDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-Realm

  UserDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: realm_internal_id
          AttributeType: S
        - AttributeName: account_sub
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: realm_internal_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: account_sub_index
          KeySchema:
            - AttributeName: account_sub
              KeyType: HASH
          Projection:
            ProjectionType: ALL      
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-User

  AccountDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: sub
          AttributeType: S
      KeySchema:
        - AttributeName: sub
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-Account

  AccountAttributeDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: account_sub
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: account_sub
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-AccountAttribute

  SessionDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: access_token
          AttributeType: S
      KeySchema:
        - AttributeName: access_token
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-Session

  RealmDomainDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: domain
          AttributeType: S
      KeySchema:
        - AttributeName: domain
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-RealmDomain

  PasswordResetTokenDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: sub
          AttributeType: S
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: sub
          KeyType: HASH
        - AttributeName: token
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: password_reset_token_token_index
          KeySchema:
            - AttributeName: token
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-PasswordResetToken
