username: GitHub-CI
icon_url: https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/community/logos/python-logo-only.png

pretext: Acionado via {{eventName}} por {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
title_link: https://support.github.com

text: |
  *<{{workflowRunUrl}}|Fluxo de trabalho _{{workflow}}_ trabalho _{{jobName}}_ acionado por _{{eventName}}_ está _{{jobStatus}}_>* por <{{refUrl}}|`{{ref}}`>
  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
  {{#if payload.commits}}
  *Commits*
  {{#each payload.commits}}
  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
  {{/each}}
  {{/if}}

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} está {{jobStatus}}

fields:
  - title: Etapas do trabalho
    value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
    short: false
  - title: Matriz de trabalho
    value: "{{#each jobMatrix}}{{@key}}: {{this}}\n{{/each}}"
    short: false
  - title: Fluxo de trabalho
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Referência do Git
    value: "{{ref}} ({{refType}})"
    short: true
  - title: ID de execução
    value: |-
      <{{workflowRunUrl}}|{{runId}}>
    short: true
  - title: Número de execução
    value: "{{runNumber}}"
    short: true
  - title: Ator
    value: "{{actor}}"
    short: true
  - title: Status do trabalho
    value: "{{jobStatus}}"
    short: true

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
